### ISSUE TITLE
Homepage/versions as listed on npmjs.com

### ISSUE THREAD

**Issue by icleolion** [vuetifyjs/eslint-plugin-vuetify#14]
In vscode, the online package info fetched by the npm extension is garbled for eslint-plugin-vuetify and is missing the handy link to this repository:
![image](https://user-images.githubusercontent.com/47498402/71835615-e8b4f100-30a9-11ea-8f1d-dba5b76901d2.png)

For vuetify this appears properly:
![image](https://user-images.githubusercontent.com/47498402/71835535-b60af880-30a9-11ea-8eac-761af0254cd5.png)

Never published a package so not really sure what's wrong.

Also thanks for releasing beta.6, the warnings after an npm install were annoying.  Unfortunately I didn't know about this release until now due to beta.5 being tagged as `latest` and beta.6 tagged as `beta` for the versions as listed on npmjs.com.  This confused the Version Lens extension i'm using in vscode under default settings.

With beta.5 installed and default settings:
![image](https://user-images.githubusercontent.com/47498402/71835809-67119300-30aa-11ea-9d85-f7f070fb2c06.png)

It wasn't until I turned on additional functionality in the extension that it then showed me another beta had been released:
![image](https://user-images.githubusercontent.com/47498402/71835855-8c060600-30aa-11ea-9486-f4d5ee8985e5.png)

Then going back to default settings after beta.6 is installed:
![image](https://user-images.githubusercontent.com/47498402/71939669-67458780-31ab-11ea-98a7-fec709495e92.png)

**Comment by KaelWD** [comment]
>  beta.5 being tagged as latest and beta.6 tagged as beta for the versions as listed on npmjs.com

ugh, thanks. John did the last release and he uses some dumb tool that tries to be helpful.
