### ISSUE TITLE
What does no-deprecated-classes do?

### ISSUE THREAD

**Issue by benmccann** [vuetifyjs/eslint-plugin-vuetify#25]
[The docs](https://github.com/vuetifyjs/eslint-plugin-vuetify/blob/master/docs/rules/no-deprecated-classes.md) just say "fill me in"

Does this rule refer to CSS classes or JS classes?

If JS classes, is that something different than components? (requested in https://github.com/vuetifyjs/eslint-plugin-vuetify/issues/21)

**Comment by KaelWD** [comment]
CSS classes, some were removed in vuetify 2.

You can see the list it uses here: https://github.com/vuetifyjs/eslint-plugin-vuetify/blob/master/lib/rules/no-deprecated-classes.js#L16

Class changes are documented here: https://vuetifyjs.com/en/getting-started/upgrade-guide/#grid
