### ISSUE TITLE
Interest in Pug Support

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/eslint-plugin-vuetify#4]
I'm making this issue to help with measuring interest in adding pug support to the linter plugin... Starting with myself. I would like this feature.

**Comment by Heartnett** [comment]
I agree, please add pug support.

**Comment by d2phap** [comment]
Please add pug support !

**Comment by KaelWD** [comment]
This was never going to be actual support for pug, just an option to convert it to HTML instead. This is more of a one-time operation and there are already tools to do it such as https://github.com/leo-buneev/pug-to-html
