### ISSUE TITLE
It can be used on pug templates !

### ISSUE THREAD

**Issue by qnp** [vuetifyjs/eslint-plugin-vuetify#46]
Thanks to [eslint-plugin-vue-pug](https://github.com/rashfael/eslint-plugin-vue-pug), this plugin works for pug templates. I tested eslint configuration:
```
"extends": [
    "plugin:vue/vue3-recommended",
    "plugin:vue-pug/vue3-recommended",
    "plugin:vuetify/base"
 ]
```

so the doc should be updated accordingly

**Comment by KaelWD** [comment]
I have no interest in officially supporting this.
