### ISSUE TITLE
[Bug]: Absolute prop for v-progress-linear exists but shows error

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/eslint-plugin-vuetify#50]
When I use the `absolute` prop for v-progress-linear I get an error that it's been removed, but the v3 documentation still lists the `absolute` prop. I'm using `v2.0.0-beta.2`.

See https://vuetifyjs.com/en/api/v-progress-linear/#props-absolute

**Comment by KaelWD** [comment]
5b01cb647a35a35e571a7d8a8837357b103d9c41

Forgot to release after that, should be fine now.
