### ISSUE TITLE
False `no-deprecated-props` error  on VListItem

### ISSUE THREAD

**Issue by abea** [vuetifyjs/eslint-plugin-vuetify#61]
VListItem throws an error for the `ripple` prop for `vuetify/no-deprecated-props`. That prop is listed in the docs and does have the intended effect.

**Comment by abea** [comment]
Sorry, I copied the issue description from another one I submitted. It's VListItem. I'll update the description.

**Comment by KaelWD** [comment]
Added in 3.1.2: https://github.com/vuetifyjs/vuetify/commit/705b29fd5e1f6668fb55febfb5dc8ccba92a836d
