### ISSUE TITLE
`v-range-slider` incorrectly reports `@end` event as deprecated

### ISSUE THREAD

**Issue by jonasengelmann** [vuetifyjs/eslint-plugin-vuetify#74]
When I try to use the `@end` event, I get this message (vuetify 3.4.0, eslint-plugin-vueitfy 2.1.0):

`VRangeSlider: @end has been removed  vuetify/no-deprecated-events`

However, `@end` does work and has been ported according to this [PR](https://github.com/vuetifyjs/vuetify/pull/16514). It is also listed in the documentation. However, I also found [this](https://github.com/vuetifyjs/vuetify/issues/15675) vuetify issue, which remains open for some reason.

This also applies to the `@start` event and v-slider componenet.

**Comment by philgeronegit** [comment]
I also have the bug for the `@start` event (vuetify 3.4.0, eslint-plugin-vueitfy 2.1.0):
`VSlider: @start has been removed`

**Comment by boutils** [comment]
Same issue with same versions here.
