### ISSUE TITLE
[BUG] `v-autocomplete` incorrectly reports `value-comparator` as deprecated

### ISSUE THREAD

**Issue by philgeronegit** [vuetifyjs/eslint-plugin-vuetify#75]
When I try to use the `value-comparator` props, I get this message (vuetify 3.4.0, eslint-plugin-vueitfy 2.1.0):

`error  'value-comparator' has been removed`

However, it is listed in the [documentation](https://vuetifyjs.com/en/api/v-autocomplete/#props).

**Comment by boutils** [comment]
Same issue with same versions here.
