### ISSUE TITLE
Tslint?

### ISSUE THREAD

**Issue by ZwapKillrath** [vuetifyjs/eslint-plugin-vuetify#8]
Probably a stupid question. But we use TSlint and only have the tslint.json file. Can we use the eslint-plugin-vuetify settings here somehow?

**Comment by KaelWD** [comment]
No, this depends on eslint-plugin-vue and vue-eslint-parser. You can do the opposite though by using eslint-plugin-typescript instead of tslint, or a combination of tslint for ts and eslint for vue templates.

**Comment by MartinX3** [comment]
Tslint gets deprecated and merged with eslint

https://github.com/palantir/tslint/issues/4534

**Comment by KaelWD** [comment]
Yeah that too
