### ISSUE TITLE
[v-overlay] missing attribute "opacity"

### ISSUE THREAD

**Issue by michael-roth** [vuetifyjs/eslint-plugin-vuetify#89]
The `v-overlay` component does not know the `opacity` attribute. 

I get the error message "ESLint: 'opacity' has been removed(vuetify/no-deprecated-props)".

It was added in https://github.com/vuetifyjs/vuetify/issues/19182 though and is included in the API docs: https://dev.vuetifyjs.com/en/api/v-overlay/#props-opacity

eslint-plugin-vuetify: v2.1.1
vuetify: v3.5.3

![image](https://github.com/vuetifyjs/eslint-plugin-vuetify/assets/3627625/45c87a21-488e-4985-8d19-3f9d786d1410)

**Comment by KaelWD** [comment]
850778f8
