### ISSUE TITLE
"The activator slot must be bound" doesn't go away

### ISSUE THREAD

**Issue by varna** [vuetifyjs/eslint-plugin-vuetify#9]
I updated my template with activator slot, but my browser console is still screaming about `[Vuetify] The activator slot must be bound, try '<template v-slot:activator="{ on }"><v-btn v-on="on">'`

template:
```vue
  <v-menu
    :close-on-content-click="false"
    :rules="[isRequired]"
    v-model="menu"
    transition="scale-transition"
    offset-y
    full-width
    min-width="562px"
  >
    <template v-slot:activator="{ on }">
      <v-text-field
        :value="string"
        :rules="[isRequired]"
        :label="$t('date')"
        readonly
        v-on="on"
      />
    </template>
    <div>
      <v-date-picker v-model="date" />
      <v-time-picker v-model="time" format="24hr" width="272" />
    </div>
  </v-menu>
```

**Comment by jacekkarczmarczyk** [comment]
That's not related to the eslint plugin. Also we require a reproduction for bugs

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
