### ISSUE TITLE
border migration util matches to much

### ISSUE THREAD

**Issue by adrianjost** [vuetifyjs/eslint-plugin-vuetify#92]
The border migration regex matches too many classes and is therefor always attempting to migrate our custom defined class `border-right-default` with `border-eight-default`.

https://github.com/vuetifyjs/eslint-plugin-vuetify/blob/1b87c8384879fe7c72b7b72dac99bceb8ccdd7ba/src/rules/no-deprecated-classes.js#L16

**Comment by KaelWD** [comment]
I can't actually find these in v2 at all, this rule shouldn't exist in the first place.

**Comment by adrianjost** [comment]
I think this rule referred to the following change and might still be necessary?

> left and right have been replaced by start and end respectively. This applies to utility classes too, for example .border-r is now .border-e.

https://vuetifyjs.com/en/getting-started/upgrade-guide/#styles-and-utility-classes:~:text=left%20and%20right%20have%20been%20replaced%20by%20start%20and%20end%20respectively.%20This%20applies%20to%20utility%20classes%20too%2C%20for%20example%20.border%2Dr%20is%20now%20.border%2De.

**Comment by KaelWD** [comment]
That's wrong too I guess: 
![Screenshot_20240416_154747](https://github.com/vuetifyjs/eslint-plugin-vuetify/assets/16421948/7c36b0c7-12a0-4b20-80e2-edf2d5c5c0f1)
