### ISSUE TITLE
Error finding rule definition for no-deprecated-imports

### ISSUE THREAD

**Issue by taylorwebber** [vuetifyjs/eslint-plugin-vuetify#95]
I'm seeing an error pop up when utilizing version 2.3.0. It appears that the rule for `vuetify/no-deprecated-imports` is failing to find it's definition.

<img width="905" alt="image" src="https://github.com/vuetifyjs/eslint-plugin-vuetify/assets/155460723/21806159-3c6e-4360-9a8f-eac55295d06e">

I've double checked my configuration and it seems like everything else vuetify rule wise is working as expected. Let me know if you need additional information.

**Comment by KaelWD** [comment]
Are you still getting this? Have you deleted node_modules and restarted vscode?

**Comment by taylorwebber** [comment]
@KaelWD Looks like that did the trick 👍
